#!/bin/sh
lock() {
    i3lock -c 000000 -i ~/Pictures/wallpapers/floor.png
    # i3lock -c 000000 -i ~/Pictures/wallpapers/antergos_wallpaper_05_by_chrisflr-da3yk4r.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff -i
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
